### PR TITLE
Friend v2

### PR DESCRIPTION
**Pull request by Takhmina175**
Filter user's posts and current_user's friends' posts on the timeline page.
Use Bootstrap to improve profile image and timeline page.

### CODE REVIEW

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Guys

THIS IS VERY IMPRESSIVE WORK. YOU HAVE DONE A GOOD JOB :+1:
However, there are some changes that you need to make in order to get your project approved


- [x] There should be NO logic in the views


- [x]  thanks to this, we can find user friends only by user_id in the friendships table

      ex. 

      # User model

      has_many :confirmed_friendships, -> { where accepted: true }, class_name: "Friendship"
      has_many :friends, through: :confirmed_friendships

 - [x] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)


          ex. 
    
          # User model
    
          # Users who requested to be friends (needed for notifications)
          has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
          has_many :friend_requests, through: :inverted_friendships


- [x] in order to get all posts written by a user on their friends, you can use the simple method in the User model

      def friends_and_own_posts
        Post.where(user: (self.friends.to_a << self))
        # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
      end



Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Comment by gdumani** [comment]
1. Corrected by moving logic to the Post Controller.
2. This code performs the same function as the suggested code in a single line and is adjusted to our table schema: 
`  has_many :friends, -> { where(friendships: { status: 'accepted' }).order('name') }, through: :friendships`
3. We are using a different schema using pending friendships in place of inverted friendships and the logic to validate both ways when the acceptance is given.
4. The login we used in the view was moved to the controller and performs the same function.

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] Delete friend functionality is appealing.
- [ ] PR title and summary are descriptive.
- [ ] README is professional and contains all the necessary info to run the project locally.
## To Improve 🙏
- [x] Please add the instructions on how to run spec tests in the README file.
- [x] User should only see his posts and posts by his friends. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png).
- [x] Please delete commented code from friendship spec.

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Comment by gdumani** [comment]
The second improvement requested is already there. This code provides that functionality:
``` 
def timeline_posts
    @timeline_posts ||= Post.all.ordered_by_most_recent.includes(:user).where(
      user: [current_user.friends, current_user].flatten
    )
  end
```

**Review by elisha2kyakpo1 — APPROVED** [review]
# Status: Approved💪✔🎉
Congratulations! Keep it up, I'm happy to see all the changes requested by previous reviewers being implemented.

You can reach out to me on slack as elisha kyakopo, if you have any questions.

**Pull request merged**
